[package]
name = "tango-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-multipart = "0.6.1"
actix-web = "4.4.0"
async-process = "2.0.0"
async-trait = "0.1.74"
base64 = "0.21.4"
bcrypt = "0.15.0"
chrono = { version = "0.4.31", features = ["serde"] }
config = "0.13.3"
derive_more = "0.99.17"
dotenv = "0.15.0"
futures = "0.3.28"
image = "0.24.7"
itertools = "0.11.0"
jsonwebtoken = "8.3.0"
log = "0.4.20"
log4rs = "1.2.0"
md5 = "0.7.0"
num = "0.4.1"
once_cell = "1.18.0"
parse-size = "1.0.0"
regex = "1.10.1"
reqwest = { version = "0.11.22", features = ["multipart"] }
rust-s3 = "0.33.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sqlx = { version = "0.7.2", features = ["runtime-tokio", "tls-native-tls", "mysql", "macros", "chrono"] }
tempfile = "3.8.1"
uuid = { version = "1.4.1", features = ["v4"] }
